# Generated by Django 5.2.11 on 2026-05-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='quantidade_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='quantidade_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='tipo',
            field=models.CharField(choices=[('simples', 'Meta simples'), ('progresso', 'Meta por progresso')], default='simples', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='unidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
